program: EM_main.py
method: bayes
metric:
  goal: minimize
  name: CV Loss
parameters:
  Window:
    values:
      - gaussian
      - rectangular
      - linear
      - exponential
    distribution: categorical
  WindowSize:
    values: [3,5,7,9,11,13,17,21]
  WindowParameter:
    max: 15
    min: 1
    distribution: uniform