# General Parameters
snr: 6 # in [dB]
signal_length: 360 # Timesteps in an ecg signal
gpu: False # Whether we want to try to use a gpu or not
wandb: False
EM_Its: 20

# Taylor Model parameters
Window: 'gaussian'
WindowSize: 5
WindowParameter: 3
TaylorOrder: 5